### ISSUE TITLE
Weekly_weather.scss file issue

### ISSUE THREAD

**Issue by lobytek** [Smittey/Weekly-Weather#1]
When running my dash.erb via my browser at 192.168.1.116:3030/dash, I encounter an error " Sass: : SyntaxError: Invalid CSS after "...-color: #31558F" : expected selector or at-rule, was ".widget-weekly-..." in /root/dashboard/widgets/weekly_weather.scss:3

My weather.scss file in / root / dashboard / widgets / weekly_weather is exactly the same as the one here. I tried 3 times to delete and submit this file without success ... I need your help because I find this widget really nice !

**Comment by Smittey** [comment]
Hi @lobytek 

Thanks for the kind feedback! And thanks for raising this issue. I'll investigate ASAP and get back to you

Andy

**Comment by Smittey** [comment]
I'm unfortunately unable to recreate this issue.

Steps I took:

1) Created a new dashing project 

```
dashing new test-dashboard
cd test-dashboard
bundle
```

2) Imported the job `rb` file and changed the required variables, widgets folder, assets, and dashboard

3) Ran the project
`dashing start`

Can you check that your dashing project has `sass` included? My dashing comes with `sass (~> 3.2.12)` and all of this worked right out of the box

**Comment by Smittey** [comment]
Closing this issue as unable to reproduce and no response from original poster.
